yarnPath: .yarn/releases/yarn-2.4.1.cjs
nodeLinker: pnp
enableGlobalCache: true
enableTelemetry: false
logFilters:
  - level: "discard"
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
